// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiamcW-YOKnP6KtRiHcvlDlwPNL5SJdW4',
    appId: '1:776433309839:web:e0b59415e20e611ce738fa',
    messagingSenderId: '776433309839',
    projectId: 'flutter-test-app-5a3aa',
    authDomain: 'flutter-test-app-5a3aa.firebaseapp.com',
    storageBucket: 'flutter-test-app-5a3aa.appspot.com',
    measurementId: 'G-TB9JVCH5RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqn-xTLIu5PvE7aPLQpE_HQLr79r8U-6c',
    appId: '1:776433309839:android:d979e36ebcecd6fce738fa',
    messagingSenderId: '776433309839',
    projectId: 'flutter-test-app-5a3aa',
    storageBucket: 'flutter-test-app-5a3aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuScsZzVHsY_hTnlcVZSryVRMrbUpdlWg',
    appId: '1:776433309839:ios:3bb97670b7bf036ee738fa',
    messagingSenderId: '776433309839',
    projectId: 'flutter-test-app-5a3aa',
    storageBucket: 'flutter-test-app-5a3aa.appspot.com',
    iosClientId: '776433309839-agtji4e6rbbcil4scuv60hcoff5q5lvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfire',
  );
}
